spring.application.name=Competitive-Exam-Simulator
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Student
spring.datasource.username=postgres
spring.datasource.password=1234rane
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
ddl-auto=create

jwt.secret=jkjkjgjhgggjgjgjgjgjgjgjgjjjhgjhhjhfhgfhghghg
jwt.expiration=86400000

gemini.api.key=AIzaSyCoOovIwQWpp8C-RbtsoeHKPmkVXX2pka4